[package]
name = "hopium"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.0"
raylib = { version = "5.0", features = [ "wayland" ] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.119"

